### ISSUE TITLE
Reposition Halloween page button on home.html

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#103]
It is out of place, can you style it and place it somewhere more visible?

**Comment by d3vil0p3r** [comment]
@sudz123 I'm taking this 👍

**Comment by d3vil0p3r** [comment]
@sudz123 checkout #111

**Comment by DillonSimeone** [comment]
I've came up with something pretty cool. You'll need to merge my pull requests, all of them, to get it working.

Pull requests:

#145 HTML edits
#146 JavaScript edits
#147 CSS edits
#148 New image, replace the file in this with the image linked in it or something alike.

**Comment by DillonSimeone** [comment]
#175 resolves this, on the styling font. Infinite scrolling Halloween button. 

As for the placement... Hmm. Perhaps in the header along with the other nav buttons?
