### ISSUE TITLE
Make the footer movable.

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#117]
Currently it takes up 33% of the screen, is kinda irritating.

**Comment by maliMirkec** [comment]
@sudz123 Could you provide more information? A screenshot maybe?

**Comment by sudz123** [comment]
Checkout the footer in GitHub.com is it always visible to you when you are scrolling? I want something like that.

**Comment by maliMirkec** [comment]
@sudz123 I see. I could help you. 👍 

Btw, this feature is commonly known as "sticky". 😉

**Comment by maliMirkec** [comment]
@sudz123 Do you have instructions how to build the site locally?

**Comment by sudz123** [comment]
Read the readme carefully, it is pretty straightforward. Best of luck :P

**Comment by agampreetsingh** [comment]
Fixed the issue. :) 
PR #126
