### ISSUE TITLE
Remove redundant contributors.

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#169]
Above the `What is HacktoberFest` in the home page, there is a contributors section. You can see there is one in the footer too. I want only the one in the footer. Remove all the contributors from above and replace it by `Maintainers` . Put mine and Diptanshu's names there and remove our names form the footer.

**Comment by amrs-tech** [comment]
I couldn't find Diptanshu's name ?

**Comment by sudz123** [comment]
I'll add him later, his page is not linked to this repo I guess.
