### ISSUE TITLE
Add profile card.

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#170]
Once Issue #169 is taken care of, I want profile cards for the maintainers. If you want you can also add these cards in your website. Here is a [link](https://www.w3schools.com/howto/howto_css_profile_card.asp).

This is one type, you can add anything you feel is better. If you can find a photo of me, very well. Otherwise leave that to me.

**Comment by Apoorva-13** [comment]
hi can i work on this??

**Comment by sudz123** [comment]
Sure, you can either add to the home page by changing the maintainers buttons to cards. Info is on linkedin(see contributors.md) or you can add to sudz.html

**Comment by Apoorva-13** [comment]
![image](https://user-images.githubusercontent.com/31508100/46579904-bb593d80-ca37-11e8-8c67-5c235e97035f.png)
i need to replace this with a card right?
