### ISSUE TITLE
Add the hacktoberfest teaser above the footer in the home page

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#172]
[Here](https://www.youtube.com/watch?v=wPlTQjOEPWo) is the link.

**Comment by speedytechdev** [comment]
@sudz123 Do you want the video to autoplay?

**Comment by mathagician** [comment]
@sudz123 please close the issues that are resolved. That is a good practice and shall prevent precious time of users.

**Comment by sudz123** [comment]
@speedytechdev Yes autoplay sounds great.
