### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#173]
I realised that the instructions for HTML files have too big images. Secondly it would look better in a Readme in the src folder. Make the images smaller and add a readme to src after removing the main readme content. Also think of more readmes for scripts and styles folder. Can also contain info about css and javascript.

**Comment by bhefty** [comment]
I'd like to take this one. To clarify, you are looking to move the "How to run the HTML page" content of the current README into a separate README located in the src folder, while keeping the remaining README content in the root directory?

**Comment by sudz123** [comment]
Yup more or less. Also try to change the size of the images and make it a bit smaller. Another thing, can I do something similar for telling users how css and javascript works? You can submit 3 PRs for these.

**Comment by bhefty** [comment]
Sure, I'll get to work on these!
