### ISSUE TITLE
Need better front end

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#212]
I need one major aesthetic change to the front end of home.html hopefully by a UI designer. I will merge the best PR and his/her name will go in the **Hall of Fame** on this repository. I need a teaser video on home.html as given by #172 . Also I need to remove the contributors names from top of the #About and only keep it in the footer. All links should be proper. I need space for blogs as given in  #165. See what all you can change in home.html. I will keep this as the final design. There will be a designed by `author` in the page in the footer. Only the best PR will be accepted for this one.Evaluation will be within 24 hours.

**Comment by sudz123** [comment]
@sarahperea @bigseaadam @DillonSimeone @alangordon  Do take a look if you are interested. You guys have contributed quite a bit.

**Comment by jenniferkaplannyc** [comment]
I might be able to help. Can you provide a URL so I can see how it looks now?

**Comment by sarahperea** [comment]
Hi @sudz123 , I would love to give it a try! I'll try to fix some issues as well. Thanks! :)

**Comment by sudz123** [comment]
@sarahperea Here are a few more tiny changes if you are interested: 
- Change Images from beaches to something hacktoberfesty
- Remove the small gap between contact form and footer
- Get the next and prev button working
- Add a "designed by Sarah" in the footer or the header, wherever you think it fits 
Once these are done I will release a github live website

**Comment by sarahperea** [comment]
Hi @sudz123 , I made PRs for my fixes on:
- Change Images from beaches to something hacktoberfesty
- Remove the small gap between contact form and footer
- Get the next and prev button working (new design)
- Add a "designed by Sarah" in the footer
- moved the Halloween Page button in the header nav
- added 'Watch Teaser'  button in the header nav

Hope you like it! :) You can tag me if more changes are needed. :)

**Comment by sudz123** [comment]
@sarahperea As I promised, check the footer of the main README :)

**Comment by sarahperea** [comment]
Thank you @sudz123 , really made my day! :D <3
