### ISSUE TITLE
Buttons on home page 

### ISSUE THREAD

**Issue by abisummers** [sudz123/Happy_Hacking#239]
When you click the next button on the home page (src/home.html), the picture changes (after the second click) but makes all other pictures disappear. When you click the previous button, nothing happens. On the home.js `getElementById("img")` is used in the displayNextImage function but I think that should be different since img is never used as a ID.

I'm going to try and fix them if I have time, but they're open for whoever wants to try to fix them!

**Comment by sudz123** [comment]
I have referenced this in #212 . Do take a look at this and the other issues I have addressed there. I am soon going to lock the appearance of the front end in home.html, these are the last remaining changes I want. What would be great is that next button and prev button fast-forward the scrolling in the respective directions.

**Comment by sudz123** [comment]
This has been fixed lately. Closing this.
