### ISSUE TITLE
Excess spacing between the contact section and the footer (in mobile, tablet mode)

### ISSUE THREAD

**Issue by vjs3** [sudz123/Happy_Hacking#251]
There is excessive spacing in multiple sections of the website when we see it in the mobile more or any other size besides the desktop mode. I would like to start by fixing the contact section and then move on to other sections. I am attaching the image for better understanding.

Let me know if I can work on it :)
<img width="304" alt="screen shot 2018-10-12 at 11 56 20 am" src="https://user-images.githubusercontent.com/11405622/46862922-51b1a880-ce16-11e8-9cc0-abdf7cde3d4e.png">

**Comment by sudz123** [comment]
Sure have a go, tell me your method too :)

**Comment by sudz123** [comment]
I think this has been reesolved, do let me know if it isnt

**Comment by vjs3** [comment]
@sudz123 I checked it just now and it still exists for the contact section, its fixed for the video section.

**Comment by vjs3** [comment]
If you will have a look at #257 it actually fixes the issue :)
