### ISSUE TITLE
Cleaning up the CSS and proper indentation

### ISSUE THREAD

**Issue by vjs3** [sudz123/Happy_Hacking#258]
The CSS files have an improper indentation and some bad practices. I would love to fix it starting with home.css. Later on, we can make a style guideline as well to have a consistent behavior throughout the files.
Give me a heads-up if that's ok?

**Comment by sudz123** [comment]
Sure have a go :)

**Comment by dharmadev108** [comment]
I'd be willing to give a hand: is that ok?

**Comment by vjs3** [comment]
@dharmadev108 I have already started working on it. I think you can make more changes once I submit the initial PR :)

**Comment by vjs3** [comment]
@sudz123 have a look at #263 :)

**Comment by vjs3** [comment]
I have submitted the PR, once its merged have a look at some of the changes and if you want you can add them in the CSS guideline :)
