### ISSUE TITLE
Changing the language in Readme

### ISSUE THREAD

**Issue by vjs3** [sudz123/Happy_Hacking#266]
Hey @sudz123 and @diptanshu-sopho 

I wanted to discuss the current language of the README. Since the project is big and a lot of people are contributing to it, it will be great to have a nice tone to the readme specially loads of folks are new to open source :)
https://github.com/sudz123/Happy_Hacking#bookmark-important-bookmark

Here instead of "styles I want all the css files in this folder with proper nomenclature." We can put something like "please put all css files in this folder" something like that.

Hope you got my point :) Its just a good open source practice. Let me know what do you guys think of it?

**Comment by diptanshu-sopho** [comment]
Your suggestion is good. @sudz123 will also agree. So, if you want to do these changes, go ahead.

**Comment by vjs3** [comment]
@diptanshu-sopho cool. I will do the changes and will send the PR for the same.
