### ISSUE TITLE
Need a Halloween page!

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#28]
Well Halloween is coming up at the month end. Lets add a page through a link in the home.html. Make sure it has some description and a few spooky images.

**Comment by yurichandra** [comment]
Is there any guide about html page that i could workin on?

**Comment by sudz123** [comment]
You have complete freedom. Make it spooky. Google what you don't know. Add a link on the home page

**Comment by yurichandra** [comment]
I'll doing it.
