### ISSUE TITLE
Home page needs a menubar

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#31]
Add a title saying "Happy Hacking". Anything more is welcome.

**Comment by ferdhika31** [comment]
Can I install bootstrap for your menubar? :grinning:

**Comment by sudz123** [comment]
Everyone has complete freedom to do whatever you like. The PR which has better code and has been submitted first will be accepted. Make sure you reference the issue in the PR.

**Comment by nibiru2O12** [comment]
https://github.com/sudz123/Happy_Hacking/pull/44#issue-219994547

**Comment by DillonSimeone** [comment]
I think this was resolved by #150, and #49.
