### ISSUE TITLE
header modification

### ISSUE THREAD

**Issue by ishanisri** [sudz123/Happy_Hacking#369]
the header links get underlined when clicked, which will be removed

**Comment by ishanisri** [comment]
Sorry, but I made a pull request for this already

**Comment by sudz123** [comment]
#373 #368

**Comment by sudz123** [comment]
I think one of the header links still has this issue.

**Comment by ishanisri** [comment]
Yes, I think the issue is with "about"...I couldn't find anything specific to work it out, but I will keep working on that issue

**Comment by sarthak1995** [comment]
I have solved the issue, can I make a pull request?

**Comment by ishanisri** [comment]
Sure :). What was the problem?

**Comment by sudz123** [comment]
Closing this as it is solved in #388. Whenever you submit a PR try to reference it to the issue you are solving.

**Comment by sarthak1995** [comment]
@ishanisri  Header link was continue to in focus after click 

@sudz123 This was my first contribution so i wasn't aware of it. I will take care of it next time. Thanks!

**Comment by ishanisri** [comment]
@sarthak1995 Thanks 😁
