### ISSUE TITLE
Happy_Hacking... label not vertically aligned in header.

### ISSUE THREAD

**Issue by sarthak1995** [sudz123/Happy_Hacking#423]
Happy_Halloween label is not vertically aligned in header. I would like to work on the same.

**Comment by sudz123** [comment]
Sure

**Comment by sarthak1995** [comment]
@sudz123 I am having difficulty in syncing my forked repo with your original repo. Can you help me with the issue?

**Comment by sudz123** [comment]
Once you have forked the repo, make sure you make any new changes on a new branch only. After forking the repo, always do a `git pull` to make sure your local repo is updated with the upstream master. In case there are any conflicts on the branch in which you are making changes do a `git rebase master`. In case you have made changes to your master by mistake do a `git reset --hard`. Checkout the egghead.io links I have provided in the readme. Let me know if all this helps.

**Comment by sarthak1995** [comment]
@sudz123 The issue has already been fixed I guess. Please review it once and close the issue.
