### ISSUE TITLE
HomePage needs an about.

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#43]

**Comment by prekshajagetiya123** [comment]
Hey iIwould like to work on this issue!

**Comment by prekshajagetiya123** [comment]
Hey I would like to work on this issue!

**Comment by sudz123** [comment]
There is an about button, link it to a para on the page with a description about Hacktoberfest.

**Comment by shariffnour** [comment]
Hello @sudz123 I'm working on this! :)

**Comment by shariffnour** [comment]
#93 

> Hello @sudz123 I'm working on this! :)

#93 Done. Please Review
