### ISSUE TITLE
Add more points in the Readme.md

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#6]
Currently the readme.md looks bland. Lets make it more informative.

**Comment by Timtech4u** [comment]
On this @sudz123

**Comment by mufti1** [comment]
i will take it bro

**Comment by parthpandyappp** [comment]
I would like to contribute to this :)

**Comment by leader112** [comment]
@sudz123  can i contribute?

**Comment by sudz123** [comment]
Sure there are always files which need comments, codes which need descriptions. Take a look around, what part do you find difficult to understand? That part needs changes.
