### ISSUE TITLE
Take a look at the page it looks horrific.

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#70]
Make one change to one component in a PR not more please! It's difficult to review.

**Comment by sudz123** [comment]
You can make a separate file with lots of changes at a time, that is totally fine. But do not make changes to more than one components on existing pages.

**Comment by DillonSimeone** [comment]
#175 Fixes a big chuck of the nightmare.

The home.css file still need some more cleaning. There's strange stylings at the bottom that appears to be unused. 

I might get to those strange stylings in a few hours.
