### ISSUE TITLE
Modifications to the Halloween Page required

### ISSUE THREAD

**Issue by sudz123** [sudz123/Happy_Hacking#78]

**Comment by Kartikeya99** [comment]
What type of modifications are required?

**Comment by sudz123** [comment]
Be creative, what can you add? Everything is welcome.

**Comment by jChris85** [comment]
I´ve added a small easter egg for the halloween page (kids friendly)

**Comment by jChris85** [comment]
@sudz123 sure I can do that today.

**Comment by yawningpaws** [comment]
Hello, I have added a navigation bar to the Halloween page #455

**Comment by Malvikabhalla99** [comment]
Hii, I would like to add some more things in halloween page

**Comment by NeoAnoman** [comment]
Hello, I have added a custom cursor to Halloween page. #604

**Comment by vijaykrishna536** [comment]
Hi @sudz123 
I have made the countdown timer for Halloween dynamic for all the years. PR #628

**Comment by therohit777** [comment]
Hi @sudz123 
I have made a Special Magic Spells section merge it .PR #629
